### ISSUE TITLE
Generated passwords not exactly the same as original password hasher

### ISSUE THREAD

**Issue by TheQuickFox** [phreaknerd/passhash-ng#17]
When I try to login to my existing, password hasher generated accounts, I get an incompatible password. Did a slight change slip into the algorithm?

Original password hasher add-on
![password_hasher](https://user-images.githubusercontent.com/30596092/33208888-b1234130-d113-11e7-96f7-2d3df5b1dbdc.jpg)

Password hasher NG with slightly different password using same settings:
![password_hasher_ng](https://user-images.githubusercontent.com/30596092/33208870-9df7e39a-d113-11e7-9f7d-33896d8ff651.jpg)

**Comment by phreaknerd** [comment]
Interesting! I'm using an exact copy of the hashing function but I'll have a look at that. 
And I see there is an layout-issue with Firefox on windows?

**Comment by phreaknerd** [comment]
And fixed in 1.0beta-9. 
Thank you for the detailed bug description!

**Comment by TheQuickFox** [comment]
Thank you!
