### ISSUE TITLE
Configuration of last (re)loaded website is always used

### ISSUE THREAD

**Issue by gschroll** [phreaknerd/passhash-ng#18]
Thanks for your great work on this extension so far!

I stumbled upon the following problem:
Load login page of website A in the first tab and login page of website B in a second tab. If you go back to the first tab now an click on # to invoke the popup, the configuration for website B is used instead of the configuration of website A.

**Comment by phreaknerd** [comment]
Thanks for that one. I'll dive into it.

**Comment by phreaknerd** [comment]
Should be fixed in beta-10 now.
