### ISSUE TITLE
Close passhash-ng Windows with OK Button

### ISSUE THREAD

**Issue by vobexo** [phreaknerd/passhash-ng#19]
Hi,
can you change that the PW Hash-NG Window are closed by klick on the Ok Button?
Like the old original PW Hasher addon?
I dont´t want to make an extra klick on the X Button from the Window.
System: Windows10, Firefox 57.0, Ver.1.Beta-9

Thx
Ralle

[]http://www.bilder-upload.eu/show.php?file=aa6e7a-1511613854.jpg

**Comment by phreaknerd** [comment]
Fixed!

**Comment by vobexo** [comment]
Hi, 
dont fixed in FireFox 57.01 64Bit!

Ralle

**Comment by phreaknerd** [comment]
Please check this with the latest version of the addon: 1.0 
https://addons.mozilla.org/firefox/downloads/file/812045/password_hasher_ng-1.0-an+fx-linux.xpi?src=dp-btn-primary

**Comment by vobexo** [comment]
Hallo,
getestet mit Version 1.0 firefox 57,02 64Bit
Button Ok schließt das Fenster immer noch nicht!

Gruß Ralle
