### ISSUE TITLE
Layout of popup is broken

### ISSUE THREAD

**Issue by orenbenkiki** [phreaknerd/passhash-ng#21]
There's a mysterious "$$" floating above the right hand side of the Masterkey and the left hand side of the unmask checkbox. Actually, the content changes when I type in the password. Not sure what this is supposed to be.

Expanding the options doesn't increase the size enough to show all the options.

Resizing the window to be too tall causes the "Size" radio button to jump to the right, leaving the bottom empty.

I think it would be better (and simpler) if the pop-up always simply showed all the options in a fixed layout. It would be simpler to implement and more robust against issues with font sizes, zoom scales, etc.

**Comment by phreaknerd** [comment]
Duplicate of https://github.com/phreaknerd/passhash-ng/issues/15

**Comment by phreaknerd** [comment]
> There's a mysterious "$$" floating above the right hand side

See #10 : This is a feature to confirm that you've enetered the masterkey correctly without having to unmask the field.
