### ISSUE TITLE
Import/Export per-site settings

### ISSUE THREAD

**Issue by orenbenkiki** [phreaknerd/passhash-ng#25]
It would be very useful to be able to export the per-site setup (bump number, password size, special characters etc.) - say as a JSON file - and, of course, also be able to import it back in.

This would allow synchronizing between different computers, creating backups, dealing with version upgrades, etc.

**Comment by phreaknerd** [comment]
Duplicate of https://github.com/phreaknerd/passhash-ng/issues/14
