### ISSUE TITLE
Broken layout (length of password selector) in Ubuntu 16.04

### ISSUE THREAD

**Issue by pzlabuda** [phreaknerd/passhash-ng#26]
FF 57.0.1 @ Ubuntu 16.04 x64. Screen resolution is 1680x1050.

![strangelook](https://user-images.githubusercontent.com/16782621/33728288-3f2e3faa-db7a-11e7-9be1-9270296f6569.png)

**Comment by futwick** [comment]
Also a small typo, it should say "one punctuation character" not "on punctuation character".

**Comment by phreaknerd** [comment]
The layout should be fixed in 1.0. The typo will be fixed in release 1.0.1 
Thanks!
