### ISSUE TITLE
Bestimmte Webseiten funktionieren nicht mit Passhash-NG

### ISSUE THREAD

**Issue by vobexo** [phreaknerd/passhash-ng#27]
Hallo,
einige Webseiten funktionieren nicht mit Passhash-NG.

Es wird das Passwort nicht an das Eingabefeld der Webseite übergeben.

[https://www.ashampoo.com/de/eur/mlo/intro](url)
[https://www.vattenfall.de/service/login?loginFromSSO=&rmct=P](url)
[https://www.humblebundle.com/](url)

Gruß
Ralle

**Comment by vobexo** [comment]
Mit PWHash im Chrome Browser funktionieren diese Webseiten.
Die generierten Passwörter beider Browser stimmen auch überein!

Gruß
Ralle

**Comment by phreaknerd** [comment]
Gefixt in der 1.0! Danke für den bugreport!

**Comment by vobexo** [comment]
Hallo,

leider funktioniert bei Humble Bundle der Login immer noch nicht!
der # Button fzum öffnen des Passhash-NG Fensters erscheint nicht.
Öffnen des Fensters über Rechtsklick und Auswahl im Contextmenü Passhasher.
Das hehashte Password wird nicht korrekt übergeben, im Hintergrund bleibt der Text Password sichtbar
und wird von den Punkten des gehashten Passwortes überschrieben.
Das eingegeben Passwort wird dann nicht von der Webseite akzeptiert.
Es funktioniert nur, wenn das Passwort im Passwordhasher-NG sichtbar gemacht wird und dann kopiert und in das Humble Bundle Passwortfeld eingefügt wird.
![humble-bundle-pwhasher-ng](https://user-images.githubusercontent.com/15708369/34060445-139814b8-e1e4-11e7-9c76-cce6bd5e0d40.jpg)
