### ISSUE TITLE
Dialog Options >> Confusing layout of 'Size' radio buttons

### ISSUE THREAD

**Issue by iam-TJ** [phreaknerd/passhash-ng#28]
Firefox 59.0a1 (2017-12-11) (64-bit) on Ubuntu 16.04

When expanding the dialog the list of hashword sizes radio buttons is confusing and difficult to read even if the dialog is resized larger.

![screenshot from 2017-12-17 20-26-12](https://user-images.githubusercontent.com/1151442/34083444-e4b42e30-e368-11e7-90d6-0cacbb082bb1.png)

**Comment by phreaknerd** [comment]
Can you test again with 1.0.2beta2?

**Comment by phreaknerd** [comment]
Fixed with 1.0.2.
