### ISSUE TITLE
wrong Cursor focus ...

### ISSUE THREAD

**Issue by elektroschrott** [phreaknerd/passhash-ng#29]
When I open PW-Hasher by click, the focus stays correct in the field masterpassword. But if I open it by strg+f6, the focus is wrong. So it's nearly impossible to use it only by keyboard (like the old PW-Hasher).

**Comment by phreaknerd** [comment]
Seem your using ff 57 on windows?

**Comment by elektroschrott** [comment]
Yes, indeed. I hat to type TAB for 4times each time...

**Comment by phreaknerd** [comment]
That was an issue with ff. Fixed with FF 60b1.
