### ISSUE TITLE
Websides with Overlay Passwordfield don´t work with Passhash-ng

### ISSUE THREAD

**Issue by vobexo** [phreaknerd/passhash-ng#31]
Hallo,

leider funktioniert bei Humble Bundle der Login immer noch nicht!
der # Button zum öffnen des Passhash-NG Fensters erscheint nicht.
Öffnen des Fensters über Rechtsklick und Auswahl im Contextmenü Passhasher.
Das gehashte Password wird nicht korrekt übergeben, im Hintergrund bleibt der Text Password sichtbar
und wird von den Punkten des gehashten Passwortes überschrieben.
Das eingegeben Passwort wird dann nicht von der Webseite akzeptiert.
Es funktioniert nur, wenn das Passwort im Passwordhasher-NG sichtbar gemacht wird und dann kopiert und in das Humble Bundle Passwortfeld eingefügt wird.

Getestet mit FF58.0 Windows10 

Websides with Overlay Login dont work with Passhash-ng.

https://www.humblebundle.com/
click on Login open a small window with email and password fileld.
using passhash-ng for entering the Password, result in wrong Password because in Background from the Passwordfield  you can see the "Password" Letters by clicking on the OK field from Passhash-NG
Copy the Password with CTRL+C from Passhasher-Ng in the Password field works!

All Websides with Overlay Window dont work with Passhash-NG

**Comment by phreaknerd** [comment]
This is why I've implemented all options for activating the hasher:
hash symbol at the password field,
hasher icon in the location bar,
keyboard shortcut Ctrl-Shift-F6
or right-click inside the password field (which is the only option that works on the humblebundle page)
