### ISSUE TITLE
wrong sitetack

### ISSUE THREAD

**Issue by vobexo** [phreaknerd/passhash-ng#34]
Hi,
at https://www.shoop.de/ passhash-ng get a wrong sitetack!

instead of Shoop it shows cashbackdeals ?!
![shoop](https://user-images.githubusercontent.com/15708369/43473477-898951a4-94f0-11e8-83f2-1ab2394a67c7.jpg)

**Comment by vobexo** [comment]
not sure if it was my PC, on other Pc the error does not occur

**Comment by phreaknerd** [comment]
Ok, thanks. I'll close this ticket as a can't reproduce this behaviour. 
Feel free to comment on this ticket again if the error occurs again.
